export enum ConsultationType {
    CONSULTATION = 'CONSULTATION',
    VACCINATION = 'VACCINATION',
    SURGERY = 'SURGERY',
    EMERGENCY = 'EMERGENCY',
    LAB_RESULTS = 'LAB_RESULTS',
    HOSPITALIZATION = 'HOSPITALIZATION',
}